services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag_demo_pgvector
    environment:
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: rag
      POSTGRES_DB: rag_demo
    ports:
      - "5432:5432"
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
